---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-toevla-data-entry
    dry_run: true
    purge: true
trigger:
  event:
    - pull
---
kind: pipeline
type: docker
name: push-latest-build-on-commit-to-master
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-toevla-data-entry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
    - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-feature-build-for-feature-branch
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-toevla-data-entry
    tags: ${DRONE_BRANCH##feature/}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - feature/*
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release-on-tag
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-toevla-data-entry
    dry_run: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-toevla-data-entry
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: signature
hmac: cc15da2e3ceb2b06f80699a1dac41361643c12e631d6f44c8c308838cd58536f

...
